[package]
name = "nxrsbackend"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "nxrsbackend"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.31.0", features = ["nif_version_2_16"] }
faer = "0.17.1"
